### ISSUE TITLE
error msg from Task 1: Sequence and Structure Modeling

### ISSUE THREAD

**Issue by partrita** [nayoung10/ASSD#6]
When I tried to step1 of `Task 1: Sequence and Structure Modeling`.

```bash
# Step 1: Sequence design
bash scripts/k_fold_train.sh
```

Got this error msg.

```bash
Error executing job with overrides: ['experiment=esm2', 'datamodule=cdr', 'name=sabdab/cdrh3/fold_1/esm2_t33_650M_UR50D', 'trainer=ddp_fp16', 'datamodule.data_dir=${paths.data_dir}/cdrh3/fold_1', 'task.learning.cdr_type=3', 'model.name=esm2_t33_650M_UR50D', 'trainer.max_epochs=30']
Error in call to target 'pytorch_lightning.trainer.trainer.Trainer':
MisconfigurationException("CUDAAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].")
full_key: trainer

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

It seems like there's an issue with running your job due to a misconfiguration related to CUDA acceleration. Therefore, I check `Check CUDA Availability`. 

```bash
❯ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

I checked bash script and change `CUDA_VISIBLE_DEVICES` to `0`. and saw another error msg like this.

```bash
Error executing job with overrides: ['experiment=esm2', 'datamodule=cdr', 'name=sabdab/cdrh1/fold_1/esm2_t33_650M_UR50D', 'trainer=ddp_fp16', 'datamodule.data_dir=${paths.data_dir}/cdrh1/fold_1', 'task.learning.cdr_type=1', 'model.name=esm2_t33_650M_UR50D', 'trainer.max_epochs=30']
Traceback (most recent call last):
  File "/home/fkt/Downloads/AGN/train.py", line 54, in main
    return train(config)
  File "/home/fkt/Downloads/AGN/src/training_pipeline.py", line 73, in train
    trainer.fit(model=pl_module, datamodule=datamodule, ckpt_path=ckpt_path)
[skipped]
  File "/home/fkt/mambaforge/envs/AGN/lib/python3.8/site-packages/loralib/layers.py", line 140, in train
    self.weight.data += T(self.lora_B @ self.lora_A) * self.scaling
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I guess it's hardware issues. Please could you give a minimum requirements?

**Comment by nayoung10** [comment]
Here are the requirements:
  - python=3.8
  - pytorch::pytorch==1.12.0
  - pytorch::torchvision==0.13.0
  - pytorch::torchaudio==0.12.0
  - cudatoolkit=11.3
  
  We follow [ByProt](https://github.com/BytedProtein/ByProt) since we have built upon their code.
